//! This file is autogenerated! Edit in meta/scripts/GenerateMetaData.ts

export const metadata = {
	version: "1.7.1",
	packageName: "@davidnet/svelte-ui",
	npmUrl: "https://www.npmjs.com/package/@davidnet/svelte-ui",
	commitHash: "95d39c9",
	fullCommitHash: "95d39c9af3845c96779477f3fc8b8c9c184e1542",
	commitDate: "2025-07-27T13:24:53+02:00",
	branch: "main",
	commitUrl: "https://github.com/davidnet-net/svelte-ui/commit/95d39c9af3845c96779477f3fc8b8c9c184e1542",
	repoUrl: "https://github.com/davidnet-net/svelte-ui"
};
