//! This file is autogenerated! Edit in meta/scripts/GenerateMetaData.ts

export const metadata = {
  version: "1.5.8",
  packageName: "@davidnet/svelte-ui",
  npmUrl: "https://www.npmjs.com/package/@davidnet/svelte-ui",
  commitHash: "58bfbf3",
  fullCommitHash: "58bfbf36cf25360b4e237503253925d59b66b913",
  commitDate: "2025-07-07T17:44:11+02:00",
  branch: "main",
  commitUrl: "https://github.com/davidnet-net/svelte-ui/commit/58bfbf36cf25360b4e237503253925d59b66b913"
};
