import { readFileSync, writeFileSync } from 'fs';

const pkg = JSON.parse(readFileSync('./package.json', 'utf-8'));
const version = pkg.version;

const content =
    `//! This file is autogenerated! Edit in meta/scripts/GenerateMetaData.ts\n\n` +
    `export const metadata = {\n` +
    `  version: "${version}"\n` +
    `};\n`;

writeFileSync('./src/lib/metadata.ts', content);
console.log(`✅ Metadata generated ${version}`);
