//! This file is autogenerated! Edit in meta/scripts/GenerateMetaData.ts

export const metadata = {
  version: "1.5.5",
  commitHash: "f02af38",
  commitDate: "2025-07-07T14:42:52+02:00",
  branch: "main"
};
