name: Code Quality

on:
    push:
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Linting

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run lint
